### ISSUE TITLE
Error removing build directory

### ISSUE THREAD

**Issue by rixx** [palewire/django-bakery#126]
On travis CI, I'm currently experiencing an error when bakery tries to remove an existing build dir. The traceback originates from [this line](https://github.com/datadesk/django-bakery/blob/master/bakery/management/commands/build.py#L166) and can be seen in [this log](https://travis-ci.org/pretalx/pretalx/jobs/411679301#L2742).

This happens due to similtaneous execution of the testsuite in a way that will not happen in production (and that I stopped for now).

**Comment by palewire** [comment]
What do you think we could do to fix this?
